package datos;
import beans.LibroBeans; import java.sql.*; import java.util.ArrayList; import java.util.List; import util.Conexion;
public class LibroDatos {
 private static final String SELECT="SELECT l.id_libro,l.titulo,l.año_publicacion,l.id_autor,l.id_categoria,a.nombre AS autor,c.nombre_categoria AS categoria FROM libro l INNER JOIN autor a ON l.id_autor=a.id_autor INNER JOIN categoria c ON l.id_categoria=c.id_categoria ";
 public List<LibroBeans> listar(String autor, String categoria) throws SQLException { List<LibroBeans> lista=new ArrayList<>(); StringBuilder sql=new StringBuilder(SELECT+"WHERE 1=1 "); List<String> params=new ArrayList<>(); if(autor!=null&&!autor.isBlank()){sql.append("AND l.id_autor=? ");params.add(autor);} if(categoria!=null&&!categoria.isBlank()){sql.append("AND l.id_categoria=? ");params.add(categoria);} sql.append("ORDER BY l.id_libro DESC"); try(Connection cn=Conexion.obtenerConexion();PreparedStatement ps=cn.prepareStatement(sql.toString())){for(int i=0;i<params.size();i++) ps.setInt(i+1,Integer.parseInt(params.get(i))); try(ResultSet rs=ps.executeQuery()){while(rs.next()) lista.add(mapear(rs));}} return lista; }
 public void insertar(LibroBeans l) throws SQLException {String sql="INSERT INTO libro(titulo,año_publicacion,id_autor,id_categoria) VALUES(?,?,?,?)"; try(Connection c=Conexion.obtenerConexion();PreparedStatement ps=c.prepareStatement(sql)){asignar(ps,l);ps.executeUpdate();}}
 public void actualizar(LibroBeans l) throws SQLException {String sql="UPDATE libro SET titulo=?,año_publicacion=?,id_autor=?,id_categoria=? WHERE id_libro=?"; try(Connection c=Conexion.obtenerConexion();PreparedStatement ps=c.prepareStatement(sql)){asignar(ps,l);ps.setInt(5,l.getIdLibro());if(ps.executeUpdate()==0)throw new SQLException("El libro ya no existe.");}}
 public void eliminar(int id) throws SQLException {String sql="DELETE FROM libro WHERE id_libro=?";try(Connection c=Conexion.obtenerConexion();PreparedStatement ps=c.prepareStatement(sql)){ps.setInt(1,id);if(ps.executeUpdate()==0)throw new SQLException("El libro ya no existe.");}}
 private void asignar(PreparedStatement ps,LibroBeans l)throws SQLException{ps.setString(1,l.getTitulo());ps.setInt(2,l.getAnioPublicacion());ps.setInt(3,l.getIdAutor());ps.setInt(4,l.getIdCategoria());}
 private LibroBeans mapear(ResultSet rs)throws SQLException{LibroBeans l=new LibroBeans(rs.getInt("id_libro"),rs.getString("titulo"),rs.getInt("año_publicacion"),rs.getInt("id_autor"),rs.getInt("id_categoria"));l.setNombreAutor(rs.getString("autor"));l.setNombreCategoria(rs.getString("categoria"));return l;}
}
